Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.network "forwarded_port", guest: 80, host: 8081
    # config.vm.network "private_network", ip: "192.168.56.4"
    # config.vm.network "private_network", type: "dhcp"
    config.vm.network "public_network"
    config.vm.network "public_network", ip: "192.168.0.104"
  end